### ISSUE TITLE
Private Chest?

### ISSUE THREAD

**Issue by TopCastStudios** [voretaq7/BBDeathChests#1]
This isn't necessarily an issue, but I was wondering if there is a way to make a players death chest private from other players, so they lose their inventory on death, but don't have it stolen by others.
Thanks!

**Comment by voretaq7** [comment]
At the moment there's no support for chest permissions. This is by design since if you PvP someone and lose I figure they're entitled to pick over your corpse  (spoils of war and all that).
Similarly if you are using Grief prevention & die in someone else's claim your chest may be locked by that plugin (this is not ideal and may change). 

I wouldn't want to implement chest permissions in this plugin since that requires tracking chests and a bunch of other stuff that may not play nice with other plugins, but if you're using a chest permissions plugin I would consider adding support for it if their code is sane & lets me do it without jumping through too many hoops.
"lock chests" would then become a config option.

**Comment by TopCastStudios** [comment]
Okay that's all good I like the way you think
